// Mocks generated by Mockito 5.0.15 from annotations
// in nyt_app/test/features/artilces/domain/usecases/most_pop_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nyt_app/core/error/failures.dart' as _i6;
import 'package:nyt_app/features/articles/domain/entities/article.dart' as _i7;
import 'package:nyt_app/features/articles/domain/repositories/article_repository.dart'
    as _i2;
import 'package:nyt_app/features/articles/domain/usecases/most_popular.dart'
    as _i4;


class _FakeArticleRepository_0 extends _i1.Fake
    implements _i2.ArticleRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [MostPopularArticleUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockMostPopularArticleUC extends _i1.Mock
    implements _i4.MostPopularArticleUC {
  MockMostPopularArticleUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArticleRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeArticleRepository_0()) as _i2.ArticleRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>> call(
          {required _i4.MostPopularArticleParams params}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#params: params}),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  String toString() => super.toString();
}
