// Mocks generated by Mockito 5.0.15 from annotations
// in nyt_app/test/features/artilces/data/datasource/remote_data_srouce_test.dart.
// Do not manually edit this file.

import 'dart:async';

import 'package:mockito/mockito.dart';
import 'package:nyt_app/features/articles/data/datasource/articles_remote_data_source.dart';
import 'package:nyt_app/features/articles/data/Model/article_most_popular_response.dart';
import 'package:nyt_app/features/articles/data/Model/article_search_respose.dart';

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeArticleMostPopularResponse_0 extends Fake
    implements ArticleMostPopularResponse {}

class _FakeArticleSearchResponse_1 extends Fake
    implements ArticleSearchResponse {}

/// A class which mocks [ArticleRemoteDataSrouce].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRemoteDataSrouce extends Mock
    implements ArticleRemoteDataSrouce {
  // MockArticleRemoteDataSrouce() {
    // throwOnMissingStub(this);
  // }

  // @override
  // Future<ArticleMostPopularResponse> getMostPopularArticle(
  //         {required String type, required int days}) =>
  //     (super.noSuchMethod(
  //             Invocation.method(
  //                 #getMostPopularArticle, [], {#type: type, #days: days}),
  //             returnValue: Future<ArticleMostPopularResponse>.value(
  //                 _FakeArticleMostPopularResponse_0()))
  //         as Future<ArticleMostPopularResponse>);
  // @override
  // Future<ArticleSearchResponse> searchArticle({String? query}) => (super
  //         .noSuchMethod(Invocation.method(#searchArticle, [], {#query: query}),
  //             returnValue: Future<ArticleSearchResponse>.value(
  //                 _FakeArticleSearchResponse_1()))
  //     as Future<ArticleSearchResponse>);
  // @override
  // String toString() => super.toString();
}
